# Generated by Django 4.2.24 on 2026-01-02 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('matches', '0034_alter_playerframes_gold'),
    ]

    operations = [
        migrations.CreateModel(
            name='Champion',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('role', models.CharField(blank=True, max_length=32, null=True)),
                ('release_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DraftAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence_number', models.PositiveSmallIntegerField()),
                ('action_type', models.CharField(choices=[('pick', 'Pick'), ('ban', 'Ban')], max_length=4)),
                ('team_side', models.CharField(choices=[('blue', 'Blue'), ('red', 'Red')], max_length=4)),
                ('drafter_id', models.CharField(blank=True, max_length=16, null=True)),
                ('champion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='draft.champion')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='draft_actions', to='matches.game')),
            ],
            options={
                'ordering': ['sequence_number'],
                'unique_together': {('game', 'sequence_number')},
            },
        ),
    ]
