# Generated by Django 4.2.24 on 2026-01-04 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0034_alter_playerframes_gold'),
        ('draft', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='champion',
            name='release_date',
        ),
        migrations.RemoveField(
            model_name='champion',
            name='role',
        ),
        migrations.CreateModel(
            name='TeamChampionPickStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wins', models.PositiveIntegerField(default=0)),
                ('games_played', models.PositiveIntegerField(default=0)),
                ('red_side_wins', models.PositiveIntegerField(default=0)),
                ('red_side_games', models.PositiveIntegerField(default=0)),
                ('blue_side_wins', models.PositiveIntegerField(default=0)),
                ('blue_side_games', models.PositiveIntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('champion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='draft.champion')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matches.team')),
            ],
            options={
                'indexes': [models.Index(fields=['team', 'champion'], name='draft_teamc_team_id_00f6e4_idx')],
                'unique_together': {('team', 'champion')},
            },
        ),
        migrations.CreateModel(
            name='TeamChampionBanStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('games_banned', models.PositiveIntegerField(default=0)),
                ('wins', models.PositiveIntegerField(default=0)),
                ('total_self_bans', models.PositiveIntegerField(default=0)),
                ('blue_side_self_bans', models.PositiveIntegerField(default=0)),
                ('blue_side_self_wins', models.PositiveIntegerField(default=0)),
                ('red_side_self_bans', models.PositiveIntegerField(default=0)),
                ('red_side_self_wins', models.PositiveIntegerField(default=0)),
                ('total_opponent_bans', models.PositiveIntegerField(default=0)),
                ('red_side_opponent_bans', models.PositiveIntegerField(default=0)),
                ('red_side_opponent_wins', models.PositiveIntegerField(default=0)),
                ('blue_side_opponent_bans', models.PositiveIntegerField(default=0)),
                ('blue_side_opponent_wins', models.PositiveIntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('champion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='draft.champion')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matches.team')),
            ],
            options={
                'indexes': [models.Index(fields=['team', 'champion'], name='draft_teamc_team_id_44ad68_idx')],
                'unique_together': {('team', 'champion')},
            },
        ),
    ]
