# Generated by Django 4.2.24 on 2026-01-13 20:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('draft', '0002_remove_champion_release_date_remove_champion_role_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DraftSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('blue_team', models.CharField(blank=True, max_length=128, null=True)),
                ('red_team', models.CharField(blank=True, max_length=128, null=True)),
                ('picks', models.JSONField(default=dict)),
                ('bans', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'In progress'), ('COMPLETED', 'Completed')], default='IN_PROGRESS', max_length=32)),
            ],
        ),
    ]
